### PR TITLE
Most meaningful changes were pushed to last PR. Will make next pushes to this and close when ready

### PR DESCRIPTION
**Pull request by dansbecker**

### CODE REVIEW

**Comment by VikParuchuri** [comment]
This looks good to go, @dansbecker .  I'm going to merge it in.  Other changes can go into another PR.

**Comment by VikParuchuri** [comment]
I'm going to see if I can write some code to handle pushes to PRs now to avoid this in the future :)

**Comment by dansbecker** [comment]
Thanks :+1:

**Comment by VikParuchuri** [comment]
Should be fixed now!

**Pull request merged**
