### PR TITLE
Add tf/idf step and hand-selected features (re: punctuation)

### PR DESCRIPTION
**Pull request by dansbecker**

### CODE REVIEW

**Comment by dansbecker** [comment]
Made further changes after I first issued the pull request.  Not sure how to get CI to run again.  

Also, do you want us to go ahead and merge PR's to master after it passes, or is that just for you @VikParuchuri?

**Comment by VikParuchuri** [comment]
@dansbecker Looks nice!  I need to work on making the server handle push events properly -- right now, you have to close this PR and open a new one (not reopen) to get CI to run again.  

I think for now, it makes sense for me to merge, but I'm open to ways on how to make the process better.

If you get a chance to close and open a new PR, I'll go ahead and merge that one.

**Comment by dansbecker** [comment]
Just to make sure I understand: I'm going to open a new PR, but it doesn't need to be a meaningful improvement over this one.... I am just using it to get this one scored again.  I'll push to that open PR, and close it when it has something meaningful.  Am I reading that correctly?

**Comment by VikParuchuri** [comment]
The easiest way is probably just to open another PR from your same fork.  You don't need to push to it or anything -- just opening it is enough.  Then I'll merge it after the CI runs.

**Comment by dansbecker** [comment]
Ok.  I've done that.  However, I'll also explain what I've done, because I think it's probably not the right workflow.

I made some changes, pushed to my fork, open the PR, and got scored (to something like 1.05).  I then made some more changes, and pushed them to my fork.  But I hadn't closed my PR.  So they got added to it.  As you suggested, I just closed this PR... but I don't think it got rescored after I closed it and opened a new PR.  Instead, the new PR got scored.

You could imagine this leading to bad code getting merged to master, since the last commit from the first PR wasn't validated before merging.

Anyway, I should have closed my PR after my initial commit... so everything else goes to a subsequent PR.  But if I am correct that this PR didn't get validated again before it was merged, I think that's an issue.

**Pull request closed without merging**
